name: Run Tests
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Setup Python Virtual Environment
        run: python3 -m venv venv
      
      - name: Install Dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
      
      - name: Run Tests
        run: |
          source venv/bin/activate
          ./run_test.sh
